-- =====================================================================
-- ПОКЕМОН-БАТТЛ: Скрипт создания схемы базы данных Oracle (Расширенная)
-- Файл: db/01_schema.sql
-- =====================================================================

-- Очистка существующих таблиц
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
        'BATTLE_TURNS', 'BATTLE_CREATURES', 'BATTLES', 
        'PLAYER_INVENTORY', 'ITEMS', 'PLAYER_CREATURES', 
        'PLAYERS', 'CREATURE_TEMPLATES', 'ELEMENT_ADVANTAGES', 'ELEMENTS'
    )) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- 1. СТИХИИ
CREATE TABLE ELEMENTS (
    element_id VARCHAR2(20) PRIMARY KEY,
    name_ru VARCHAR2(50) NOT NULL,
    color_hex VARCHAR2(10) NOT NULL,
    icon VARCHAR2(10) NOT NULL,
    description VARCHAR2(200)
);

-- 2. МАТРИЦА СТИХИЙНЫХ ПРЕИМУЩЕСТВ
CREATE TABLE ELEMENT_ADVANTAGES (
    attacker_element VARCHAR2(20) NOT NULL,
    defender_element VARCHAR2(20) NOT NULL,
    multiplier NUMBER(3,2) DEFAULT 1.0 NOT NULL,
    CONSTRAINT pk_element_adv PRIMARY KEY (attacker_element, defender_element),
    CONSTRAINT fk_adv_attacker FOREIGN KEY (attacker_element) REFERENCES ELEMENTS(element_id),
    CONSTRAINT fk_adv_defender FOREIGN KEY (defender_element) REFERENCES ELEMENTS(element_id)
);

-- 3. БАЗОВЫЕ ШАБЛОНЫ СУЩЕСТВ (ПОКЕМОНОВ С ДРЕВОМ ЭВОЛЮЦИИ)
CREATE TABLE CREATURE_TEMPLATES (
    template_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    element_id VARCHAR2(20) NOT NULL,
    base_hp NUMBER(5) NOT NULL,
    base_attack NUMBER(4) NOT NULL,
    base_defense NUMBER(4) NOT NULL,
    base_speed NUMBER(4) NOT NULL,
    sprite_name VARCHAR2(50) NOT NULL,
    unlock_level NUMBER(3) DEFAULT 1 NOT NULL,    -- Необходимый уровень игрока
    evolution_level NUMBER(3) DEFAULT 0 NOT NULL, -- Уровень существа для эволюции (0 = макс)
    evolves_to_id NUMBER,                         -- ID следующей формы эволюции
    description VARCHAR2(300),
    CONSTRAINT fk_creature_element FOREIGN KEY (element_id) REFERENCES ELEMENTS(element_id)
);

-- 4. ИГРОКИ (Профиль, Пароль, Рейтинг Elo, Прогресс сезонов)
CREATE TABLE PLAYERS (
    player_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    db_username VARCHAR2(128) NOT NULL UNIQUE,
    password_hash VARCHAR2(256) DEFAULT 'demo' NOT NULL,
    display_name VARCHAR2(100) NOT NULL,
    level NUMBER(3) DEFAULT 1 NOT NULL,
    exp NUMBER(8) DEFAULT 0 NOT NULL,
    coins NUMBER(8) DEFAULT 150 NOT NULL,
    elo_rating NUMBER(5) DEFAULT 1000 NOT NULL,
    season_rank VARCHAR2(30) DEFAULT 'BRONZE' NOT NULL,
    battles_won NUMBER(5) DEFAULT 0 NOT NULL,
    battles_lost NUMBER(5) DEFAULT 0 NOT NULL,
    math_train_count NUMBER(5) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 5. СУЩЕСТВА ИГРОКА (КОМАНДА / КОЛЛЕКЦИЯ)
CREATE TABLE PLAYER_CREATURES (
    creature_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id NUMBER NOT NULL,
    template_id NUMBER NOT NULL,
    nickname VARCHAR2(100),
    level NUMBER(3) DEFAULT 1 NOT NULL,
    current_hp NUMBER(5) NOT NULL,
    max_hp NUMBER(5) NOT NULL,
    attack NUMBER(4) NOT NULL,
    defense NUMBER(4) NOT NULL,
    speed NUMBER(4) NOT NULL,
    is_in_team NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT fk_pc_player FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id) ON DELETE CASCADE,
    CONSTRAINT fk_pc_template FOREIGN KEY (template_id) REFERENCES CREATURE_TEMPLATES(template_id)
);

-- 6. ПРЕДМЕТЫ И ИНВЕНТАРЬ
CREATE TABLE ITEMS (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    item_type VARCHAR2(30) NOT NULL, -- 'HEAL', 'BOOST_ATK', 'EVO_STONE'
    effect_value NUMBER(5) NOT NULL,
    description VARCHAR2(200)
);

CREATE TABLE PLAYER_INVENTORY (
    inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id NUMBER NOT NULL,
    item_id NUMBER NOT NULL,
    quantity NUMBER(4) DEFAULT 1 NOT NULL,
    CONSTRAINT fk_inv_player FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id) ON DELETE CASCADE,
    CONSTRAINT fk_inv_item FOREIGN KEY (item_id) REFERENCES ITEMS(item_id),
    CONSTRAINT uq_player_item UNIQUE (player_id, item_id)
);

-- 7. ИГРОВЫЕ СЕССИИ (БОИ 1 НА 1 И PVE)
CREATE TABLE BATTLES (
    battle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player1_id NUMBER NOT NULL,
    player2_id NUMBER,
    battle_type VARCHAR2(20) DEFAULT 'PVP' NOT NULL, -- 'PVP' или 'PVE'
    status VARCHAR2(20) DEFAULT 'WAITING' NOT NULL,
    current_turn_player_id NUMBER,
    turn_number NUMBER(4) DEFAULT 1 NOT NULL,
    winner_id NUMBER,
    elo_delta NUMBER(4) DEFAULT 25 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    CONSTRAINT fk_b_player1 FOREIGN KEY (player1_id) REFERENCES PLAYERS(player_id),
    CONSTRAINT fk_b_player2 FOREIGN KEY (player2_id) REFERENCES PLAYERS(player_id),
    CONSTRAINT fk_b_turn_player FOREIGN KEY (current_turn_player_id) REFERENCES PLAYERS(player_id),
    CONSTRAINT fk_b_winner FOREIGN KEY (winner_id) REFERENCES PLAYERS(player_id)
);

-- 8. СУЩЕСТВА В БОЮ
CREATE TABLE BATTLE_CREATURES (
    battle_creature_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    battle_id NUMBER NOT NULL,
    player_id NUMBER NOT NULL,
    original_creature_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    element_id VARCHAR2(20) NOT NULL,
    current_hp NUMBER(5) NOT NULL,
    max_hp NUMBER(5) NOT NULL,
    attack NUMBER(4) NOT NULL,
    defense NUMBER(4) NOT NULL,
    speed NUMBER(4) NOT NULL,
    is_fainted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_bc_battle FOREIGN KEY (battle_id) REFERENCES BATTLES(battle_id) ON DELETE CASCADE,
    CONSTRAINT fk_bc_player FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id),
    CONSTRAINT fk_bc_orig_creature FOREIGN KEY (original_creature_id) REFERENCES PLAYER_CREATURES(creature_id),
    CONSTRAINT fk_bc_element FOREIGN KEY (element_id) REFERENCES ELEMENTS(element_id)
);

-- 9. ИСТОРИЯ ХОДОВ И АТАК
CREATE TABLE BATTLE_TURNS (
    turn_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    battle_id NUMBER NOT NULL,
    turn_number NUMBER(4) NOT NULL,
    actor_player_id NUMBER NOT NULL,
    actor_creature_id NUMBER NOT NULL,
    target_player_id NUMBER NOT NULL,
    target_creature_id NUMBER NOT NULL,
    action_type VARCHAR2(30) DEFAULT 'ELEMENTAL_ATTACK' NOT NULL,
    is_hit NUMBER(1) NOT NULL,
    is_critical NUMBER(1) DEFAULT 0 NOT NULL,
    element_multiplier NUMBER(3,2) DEFAULT 1.0 NOT NULL,
    damage_dealt NUMBER(5) DEFAULT 0 NOT NULL,
    target_remaining_hp NUMBER(5) NOT NULL,
    message VARCHAR2(400) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_bt_battle FOREIGN KEY (battle_id) REFERENCES BATTLES(battle_id) ON DELETE CASCADE,
    CONSTRAINT fk_bt_actor_p FOREIGN KEY (actor_player_id) REFERENCES PLAYERS(player_id),
    CONSTRAINT fk_bt_target_p FOREIGN KEY (target_player_id) REFERENCES PLAYERS(player_id),
    CONSTRAINT fk_bt_actor_c FOREIGN KEY (actor_creature_id) REFERENCES BATTLE_CREATURES(battle_creature_id),
    CONSTRAINT fk_bt_target_c FOREIGN KEY (target_creature_id) REFERENCES BATTLE_CREATURES(battle_creature_id)
);

CREATE INDEX idx_battles_status ON BATTLES(status);
CREATE INDEX idx_battle_turns_battle ON BATTLE_TURNS(battle_id, turn_number);
CREATE INDEX idx_players_elo ON PLAYERS(elo_rating DESC);
