-- =====================================================================
-- ПОКЕМОН-БАТТЛ: Скрипт создания роли игрока и тестовых пользователей
-- Файл: db/02_roles_and_users.sql
-- =====================================================================

-- Создание специальной роли для игроков
DECLARE
    role_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO role_exists FROM dba_roles WHERE role = 'GAME_PLAYER_ROLE';
    IF role_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE ROLE GAME_PLAYER_ROLE';
    END IF;
END;
/

-- Предоставление привилегий роли GAME_PLAYER_ROLE
-- Базовые справочники (только чтение)
GRANT SELECT ON ELEMENTS TO GAME_PLAYER_ROLE;
GRANT SELECT ON ELEMENT_ADVANTAGES TO GAME_PLAYER_ROLE;
GRANT SELECT ON CREATURE_TEMPLATES TO GAME_PLAYER_ROLE;
GRANT SELECT ON ITEMS TO GAME_PLAYER_ROLE;

-- Профиль игрока, существа и инвентарь
GRANT SELECT, INSERT, UPDATE ON PLAYERS TO GAME_PLAYER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON PLAYER_CREATURES TO GAME_PLAYER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON PLAYER_INVENTORY TO GAME_PLAYER_ROLE;

-- Игровые сессии и история ходов
GRANT SELECT, INSERT, UPDATE ON BATTLES TO GAME_PLAYER_ROLE;
GRANT SELECT, INSERT, UPDATE ON BATTLE_CREATURES TO GAME_PLAYER_ROLE;
GRANT SELECT, INSERT ON BATTLE_TURNS TO GAME_PLAYER_ROLE;

-- Синонимы (если игроки подключаются под своими схемами к схеме владельца GAME_ADMIN)
-- CREATE OR REPLACE PUBLIC SYNONYM ELEMENTS FOR GAME_ADMIN.ELEMENTS;
-- CREATE OR REPLACE PUBLIC SYNONYM BATTLES FOR GAME_ADMIN.BATTLES;
-- CREATE OR REPLACE PUBLIC SYNONYM BATTLE_TURNS FOR GAME_ADMIN.BATTLE_TURNS;
-- CREATE OR REPLACE PUBLIC SYNONYM BATTLE_CREATURES FOR GAME_ADMIN.BATTLE_CREATURES;
-- CREATE OR REPLACE PUBLIC SYNONYM PLAYERS FOR GAME_ADMIN.PLAYERS;
-- CREATE OR REPLACE PUBLIC SYNONYM PLAYER_CREATURES FOR GAME_ADMIN.PLAYER_CREATURES;

-- Создание двух тестовых пользователей БД Oracle для многопользовательского режима
DECLARE
    user_cnt NUMBER;
BEGIN
    -- Пользователь PLAYER1
    SELECT COUNT(*) INTO user_cnt FROM all_users WHERE username = 'PLAYER1';
    IF user_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER PLAYER1 IDENTIFIED BY "Player1Password#123" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    END IF;
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO PLAYER1';
    EXECUTE IMMEDIATE 'GRANT GAME_PLAYER_ROLE TO PLAYER1';

    -- Пользователь PLAYER2
    SELECT COUNT(*) INTO user_cnt FROM all_users WHERE username = 'PLAYER2';
    IF user_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER PLAYER2 IDENTIFIED BY "Player2Password#123" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    END IF;
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO PLAYER2';
    EXECUTE IMMEDIATE 'GRANT GAME_PLAYER_ROLE TO PLAYER2';
END;
/
